--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/buit/RICE/Wallpapers/CGI/vibes-of-watching-the-city-2-1920×1080.jpg"

-- Special
background="#1f1118"
foreground="#c7c3c5"
cursor="#c7c3c5"

-- Colors
color0="#1f1118"
color1="#b35951"
color2="#6379a0"
color3="#6e88c3"
color4="#be7785"
color5="#a5819f"
color6="#e57476"
color7="#c7c3c5"
color8="#574c51"
color9="#b35951"
color10="#6379a0"
color11="#6e88c3"
color12="#be7785"
color13="#a5819f"
color14="#e57476"
color15="#c7c3c5"
