# Shell variables
# Generated by 'wal'
wallpaper='/home/buit/RICE/Wallpapers/CGI/vibes-of-watching-the-city-2-1920×1080.jpg'

# Special
background='#1f1118'
foreground='#c7c3c5'
cursor='#c7c3c5'

# Colors
color0='#1f1118'
color1='#b35951'
color2='#6379a0'
color3='#6e88c3'
color4='#be7785'
color5='#a5819f'
color6='#e57476'
color7='#c7c3c5'
color8='#574c51'
color9='#b35951'
color10='#6379a0'
color11='#6e88c3'
color12='#be7785'
color13='#a5819f'
color14='#e57476'
color15='#c7c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
